const path=require('path'); const sqlite=require('node:sqlite');
require('dotenv').config({path:'/home/ecf-admin/ar-portal/.env'});
const signature=require('/home/ecf-admin/ar-portal/node_modules/cookie-signature');
const db=require('/home/ecf-admin/ar-portal/db'); db.getDb();
const email='edwin.torres@eastcoastfacilities.com'; const role=db.getUserRole(email);
const sid='diag-'+Date.now().toString(36)+Math.random().toString(36).slice(2,10);
const sess=JSON.stringify({cookie:{originalMaxAge:600000,expires:new Date(Date.now()+6e5).toISOString(),httpOnly:true,path:'/',secure:true,sameSite:'none'},user:{email,name:'Diag',role:role.role,location_filter:null,org_role:null,customer_filter:null}});
const s=new sqlite.DatabaseSync(path.join('/home/ecf-admin/ar-portal','sessions.db'));
s.exec('CREATE TABLE IF NOT EXISTS sessions (sid PRIMARY KEY, expired, sess)');
s.prepare('INSERT OR REPLACE INTO sessions (sid,expired,sess) VALUES (?,?,?)').run(sid,Date.now()+6e5,sess); s.close();
console.log('connect.sid=s%3A'+encodeURIComponent(signature.sign(sid,process.env.SESSION_SECRET||'ecf-ar-portal-secret-change-me')).replace(/%2[Ff]/g,'%2F'));
