'use strict';
// ─── corrigo.js ─────────────────────────────────────────────────────────────
// CorrigoPro Direct API client — JLL's work-order system.
//
// Edwin 2026-09-26: "I want to start building Corrigo." The goal is to stop
// working inside JLL's portal: receive work orders here, match them to sites
// and invoices, and bill without re-keying.
//
// ─── WHAT THIS DELIBERATELY DOES NOT DO ─────────────────────────────────────
// It cannot complete or check out a work order, and that is on purpose.
//
// `PUT /api/workorder/checkout` requires GEOLOCATION SHOWING THE TECHNICIAN'S
// LOCATION AT COMPLETION. Edwin 2026-09-26: "Our team currently completes work
// orders for Corrigo in Pennsylvania while the work is actually being done in
// Illinois, Ohio, and other states." CyrusOne's invoices bill out of Baltimore,
// Cincinnati, South Chicago and FacilityCare, so the spread is real.
//
// Automating completion from an office would transmit, for every work order, a
// position asserting a technician stood somewhere they did not. A person doing
// that once in a browser is their call; a system doing it at volume creates a
// different kind of record, and this one will not create it. Completion either
// moves to a surface the field actually uses, or it stays where it is.
//
// ─── CONFIGURATION ──────────────────────────────────────────────────────────
// All four values come from ONE place: the CorrigoPro Direct widget on the
// CorrigoPro Desktop home page (Admin rights required). Toggle "Integration is"
// ON, then Regenerate. No approval from JLL or Corrigo is needed — which
// corrects what this project first assumed.
//
//   CORRIGO_API_BASE      e.g. https://api.corrigopro.com   (REGION-SPECIFIC —
//                         read it off the Settings screen, do not guess; APAC
//                         is apac-api.corrigopro.com)
//   CORRIGO_OAUTH_URL     the OAuth server URL from the same screen
//   CORRIGO_CLIENT_ID     generated by Regenerate
//   CORRIGO_CLIENT_SECRET generated by Regenerate
//   CORRIGO_SUBMIT_ARMED  '1' to allow invoice submission. Default OFF, the
//                         same posture as EDI and Velocity: reading is safe,
//                         sending is not, and nothing leaves the building
//                         because a config file drifted.

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const API_BASE = (process.env.CORRIGO_API_BASE || '').replace(/\/+$/, '');
const OAUTH_URL = process.env.CORRIGO_OAUTH_URL || '';
const CLIENT_ID = process.env.CORRIGO_CLIENT_ID || '';
const CLIENT_SECRET = process.env.CORRIGO_CLIENT_SECRET || '';
const SUBMIT_ARMED = process.env.CORRIGO_SUBMIT_ARMED === '1';

// The documented prefix: https://<region>-api.corrigopro.com/direct/api/...
const PREFIX = '/direct/api';
const TIMEOUT_MS = 30000;

function configured() {
  return !!(API_BASE && OAUTH_URL && CLIENT_ID && CLIENT_SECRET);
}

/** What is set, without ever printing a secret. */
function status() {
  const mask = (v) => v ? `set (${String(v).slice(0, 4)}…, ${String(v).length} chars)` : 'MISSING';
  return {
    configured: configured(),
    submitArmed: SUBMIT_ARMED,
    apiBase: API_BASE || 'MISSING',
    oauthUrl: OAUTH_URL || 'MISSING',
    clientId: mask(CLIENT_ID),
    clientSecret: CLIENT_SECRET ? 'set' : 'MISSING',
    tokenCached: !!(_token && _token.value),
    tokenExpiresIn: _token && _token.expiresAt ? Math.max(0, Math.round((_token.expiresAt - Date.now()) / 1000)) : null,
    note: configured() ? null
      : 'Get all four from the CorrigoPro Direct widget on the CorrigoPro Desktop home page '
        + '(Admin rights): toggle Integration ON, then Regenerate. If the widget is absent, the '
        + 'company lacks Admin rights or the subscription does not include it.',
  };
}

// ─── Token ──────────────────────────────────────────────────────────────────
// Corrigo's bearer token lives 20 minutes. Refreshed at 80% of its life so a
// long sync never dies mid-way on an expiry it could have seen coming.
let _token = null;

async function token(force = false) {
  if (!configured()) throw new Error('Corrigo is not configured — see corrigo.status()');
  if (!force && _token && _token.expiresAt > Date.now()) return _token.value;

  const body = new URLSearchParams({
    grant_type: 'client_credentials',
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
  });
  const r = await fetch(OAUTH_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' },
    body,
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  const text = await r.text();
  if (!r.ok) throw new Error(`Corrigo OAuth ${r.status}: ${text.slice(0, 300)}`);
  let j;
  try { j = JSON.parse(text); } catch (e) { throw new Error(`Corrigo OAuth returned non-JSON: ${text.slice(0, 200)}`); }
  if (!j.access_token) throw new Error(`Corrigo OAuth returned no access_token: ${text.slice(0, 200)}`);
  const ttl = Number(j.expires_in) || 1200;
  _token = { value: j.access_token, expiresAt: Date.now() + ttl * 800 };  // 80% of ttl, in ms
  return _token.value;
}

/** One authenticated call. Retries ONCE on a 401, in case the token died early. */
async function call(method, route, { query, body, retry = true } = {}) {
  const qs = query ? '?' + new URLSearchParams(query).toString() : '';
  const url = `${API_BASE}${PREFIX}${route}${qs}`;
  const r = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${await token()}`,
      Accept: 'application/json',
      ...(body ? { 'Content-Type': 'application/json' } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (r.status === 401 && retry) { await token(true); return call(method, route, { query, body, retry: false }); }
  const text = await r.text();
  if (!r.ok) throw new Error(`Corrigo ${method} ${route} → ${r.status}: ${text.slice(0, 400)}`);
  if (!text) return null;
  try { return JSON.parse(text); } catch (e) { return text; }
}

// ─── Reads ──────────────────────────────────────────────────────────────────

/** Work orders by id. Documented: GET /direct/api/workOrder?ids=87340 */
async function getWorkOrders(ids) {
  const list = (Array.isArray(ids) ? ids : [ids]).filter(Boolean);
  if (!list.length) return [];
  const out = await call('GET', '/workOrder', { query: { ids: list.join(',') } });
  return Array.isArray(out) ? out : (out ? [out] : []);
}

/**
 * Work order search. The documented pattern is "everything in status X created
 * in the last N minutes", which is how a poller catches up after an outage —
 * webhooks are the primary path but they cannot be replayed.
 */
async function searchWorkOrders(opts = {}) {
  const q = {};
  if (opts.status) q.status = opts.status;
  if (opts.minutes) q.createdWithinMinutes = String(opts.minutes);
  if (opts.branchId) q.branchId = String(opts.branchId);
  const out = await call('GET', '/workOrder/search', { query: q });
  return Array.isArray(out) ? out : (out && out.items) || [];
}

/**
 * What a given customer requires on completion and invoicing — repair
 * categories, custom fields, checklists. Varies PER CUSTOMER, so nothing about
 * required fields may be hardcoded.
 */
async function customerSettings(customerId) {
  return call('GET', '/customerSettings', customerId ? { query: { customerId } } : {});
}

/** Attachments are not included in the work order payload; ask separately. */
async function getAttachments(workOrderId) {
  const out = await call('GET', '/attachments', { query: { workOrderId } });
  return Array.isArray(out) ? out : [];
}

// ─── The one write ──────────────────────────────────────────────────────────

/**
 * Submit an invoice against a work order.
 *
 * The work order must already be completed or checked out or Corrigo returns
 * error 3051 — this client cannot put it in that state (see the note at the
 * top), so a caller must find it already there.
 *
 * Gated on CORRIGO_SUBMIT_ARMED. `dryRun` returns the exact payload without
 * sending, which is how this gets reviewed before anything is transmitted.
 */
async function submitInvoice(payload, { dryRun = true } = {}) {
  if (!payload || !payload.workOrderId) throw new Error('workOrderId is required');
  if (!payload.invoiceNumber) throw new Error('invoiceNumber is required');
  if (!payload.invoiceDate) throw new Error('invoiceDate is required');
  const lines = payload.lines || [];
  if (!lines.length) throw new Error('at least one line item is required');
  for (const [i, l] of lines.entries()) {
    if (!l.description) throw new Error(`line ${i + 1}: description is required`);
    if (!Number.isFinite(Number(l.quantity)) || Number(l.quantity) === 0) throw new Error(`line ${i + 1}: quantity must be a non-zero number`);
    if (!Number.isFinite(Number(l.rate))) throw new Error(`line ${i + 1}: rate must be a number`);
  }
  if (dryRun || !SUBMIT_ARMED) {
    return { sent: false, reason: dryRun ? 'dryRun' : 'CORRIGO_SUBMIT_ARMED is not 1', payload };
  }
  const res = await call('PUT', '/invoice/submit', { body: payload });
  return { sent: true, response: res };
}

// Deliberately absent: checkout / complete / check-in. See the header.

module.exports = {
  configured, status, token, call,
  getWorkOrders, searchWorkOrders, customerSettings, getAttachments,
  submitInvoice,
};
